// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: '01-cours'}],
  tp: [{type: 'autogenerated', dirName: '02-tp'}],
  exercices: [{type: 'autogenerated', dirName: '03-exercices'}],
  //solutions: [{type: 'autogenerated', dirName: '04-solutions'}],
  notions: [{type: 'autogenerated', dirName: '05-notions'}],
};

module.exports = sidebars;
